Swift 6 (#1)
* migrate to swift 6

* up version

* Update .github/workflows/objective-c-xcode.yml

---------

Co-authored-by: Andrei Kozlov <akozlov@tradingview.com>

diff --git a/.github/workflows/objective-c-xcode.yml b/.github/workflows/objective-c-xcode.yml
--- a/.github/workflows/objective-c-xcode.yml
+++ b/.github/workflows/objective-c-xcode.yml
@@ -1,30 +1,52 @@
 name: Xcode - Build and Analyze
 
-on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+#on:
+#  push:
+#    branches: [ "main" ]
+#  pull_request:
+#    branches: [ "main" ]
 
 jobs:
   build:
     name: Build and analyse default scheme using xcodebuild command
     runs-on: macos-latest
-
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+      - name: Set Xcode version
+        uses: maxim-lobanov/setup-xcode@7f352e61cbe8130c957c3bc898c4fb025784ea1e
+        with:
+          xcode-version: latest-stable
       - name: Set Default Scheme
         run: |
           scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo $default | cat >default
+          echo "Scheme List JSON: $scheme_list"
+
+          default=$(echo $scheme_list | ruby -e "require 'json'; data = JSON.parse(STDIN.read); puts data['workspace']['schemes'][0] if data['workspace'] && data['workspace']['schemes']")
+          if [ -z "$default" ]; then
+            echo "Error: No default scheme found."
+            exit 1
+          fi
+
+          echo $default > default
           echo Using default scheme: $default
       - name: Build
         env:
           scheme: ${{ 'default' }}
         run: |
-          if [ $scheme = default ]; then scheme=$(cat default); fi
-          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
+          echo "START BUILDING"
+          if [ $scheme = default ]; then
+           scheme=$(cat default); 
+          fi
+          echo "Setting scheme $scheme"
+          cd Mokay
+          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then 
+           filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; 
+           echo "Setting workspace file to build $file_to_build"
+          else 
+           filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`";
+           echo "Setting xcodeproj file to build $file_to_build"
+          fi
           file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
+          echo "Building $file_to_build using scheme $scheme"
+          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build"
