Update .github/workflows/objective-c-xcode.yml

diff --git a/.github/workflows/objective-c-xcode.yml b/.github/workflows/objective-c-xcode.yml
--- a/.github/workflows/objective-c-xcode.yml
+++ b/.github/workflows/objective-c-xcode.yml
@@ -35,6 +35,12 @@ jobs:
           scheme: ${{ 'default' }}
         run: |
           scheme=$(cat default)
+          if [ -d "Mokay" ]; then
+            cd Mokay
+          else
+            echo "Error: Mokay directory not found."
+            exit 1
+          fi
           if [ -f *.xcworkspace ]; then
             filetype_parameter="workspace"
             file_to_build=$(ls *.xcworkspace)
