Update .github/workflows/objective-c-xcode.yml

diff --git a/.github/workflows/objective-c-xcode.yml b/.github/workflows/objective-c-xcode.yml
--- a/.github/workflows/objective-c-xcode.yml
+++ b/.github/workflows/objective-c-xcode.yml
@@ -43,11 +43,14 @@ jobs:
           fi
           if [ -f *.xcworkspace ]; then
             filetype_parameter="workspace"
-            file_to_build=$(ls *.xcworkspace)
+            file_to_build=$(ls *.xcworkspace | head -n 1)
           else
             filetype_parameter="project"
-            file_to_build=$(ls *.xcodeproj)
-          fi
+            file_to_build=$(ls *.xcodeproj | head -n 1)
+          else
+			echo "Error: No .xcworkspace or .xcodeproj file found in Mokay directory."
+			exit 1
+		  fi
 
           file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
           xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty
