Update .github/workflows/objective-c-xcode.yml

diff --git a/.github/workflows/objective-c-xcode.yml b/.github/workflows/objective-c-xcode.yml
--- a/.github/workflows/objective-c-xcode.yml
+++ b/.github/workflows/objective-c-xcode.yml
@@ -20,8 +20,15 @@ jobs:
       - name: Set Default Scheme
         run: |
           scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo $default | cat >default
+          echo "Scheme List JSON: $scheme_list"
+
+          default=$(echo $scheme_list | ruby -e "require 'json'; data = JSON.parse(STDIN.read); puts data['project']['schemes'][0] if data['project'] && data['project']['schemes']")
+          if [ -z "$default" ]; then
+            echo "Error: No default scheme found."
+            exit 1
+          fi
+
+          echo $default > default
           echo Using default scheme: $default
       - name: Build
         env:
